# Generated by Django 5.2 on 2025-04-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SehaCloneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
