# Generated by Django 5.2 on 2025-04-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SehaCloneApp', '0003_alter_centromedico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centromedico',
            name='privado',
            field=models.BooleanField(default=False),
        ),
    ]
