# Generated by Django 5.2 on 2025-04-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('icono', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=50)),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('centro_servicio', models.CharField(max_length=100)),
                ('nombre_medico', models.CharField(max_length=100)),
                ('titulo_trabajo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.IntegerField()),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='SehaCloneApp.centromedico')),
            ],
        ),
    ]
