# Generated by Django 5.2 on 2025-04-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SehaCloneApp', '0002_alter_certificado_duracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centromedico',
            options={'verbose_name': 'Centro Médico', 'verbose_name_plural': 'Centros Médicos'},
        ),
        migrations.AddField(
            model_name='centromedico',
            name='numero_licencia',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='identificacion',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
