# Generated by Django 5.2 on 2025-04-24 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SehaCloneApp', '0004_centromedico_privado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centromedico',
            options={'verbose_name': 'المركز الطبي', 'verbose_name_plural': 'المراكز الطبية'},
        ),
        migrations.AlterModelOptions(
            name='certificado',
            options={'verbose_name': 'شهادة', 'verbose_name_plural': 'الشهادات'},
        ),
        migrations.AddField(
            model_name='certificado',
            name='centro_servicio_ingles',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Center'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_inicio_lunar',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء القمري'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_salida_lunar',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء القمري'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='nacionalidad_ingles',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='nombre_medico_ingles',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doctor Name'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='nombre_paciente_ingles',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient Name'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='titulo_trabajo_ingles',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='icono',
            field=models.ImageField(upload_to='icons/', verbose_name='ايقون'),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='numero_licencia',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='رقم الترخيص'),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='privado',
            field=models.BooleanField(default=False, verbose_name='مركز خاص'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='centro_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='SehaCloneApp.centromedico', verbose_name='المركز الطبي'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='centro_servicio',
            field=models.CharField(max_length=100, verbose_name='مركز الخدمة'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رمز الإجازة'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='duracion',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha_inicio',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha_salida',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='identificacion',
            field=models.CharField(db_index=True, max_length=50, verbose_name='الهوية / الإقامة'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nacionalidad',
            field=models.CharField(max_length=50, verbose_name='جنسية'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nombre_medico',
            field=models.CharField(max_length=100, verbose_name='اسم الطبيب'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nombre_paciente',
            field=models.CharField(max_length=100, verbose_name='اسم المريض'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='titulo_trabajo',
            field=models.CharField(max_length=100, verbose_name='مسمى وظيفي'),
        ),
    ]
